name: Darwin UI

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'
          commit-message: 'chore: bumps version to {{version}} [skip ci]'
          skip-tag: 'true'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          always-auth: true
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ycensi'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run CI script
        run: yarn ci

      - name: Run unit tests
        run: yarn test

      - name: Build package
        run: yarn prepare

      - name: Publish package to GitHub
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
