name: Darwin UI

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          always-auth: true
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ycensi'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run CI script
        run: yarn ci

      - name: Run unit tests
        run: yarn test

      - name: Build package
        run: yarn prepare

      - name: "Automated Version Bump"
        uses: "maks-stupak/gh-action-bump-version@v7.1.5"
        with:
          tag-prefix: 'release-'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to GitHub
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
