name: Darwin UI

# on:
#   release:
#     types: [created]

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          always-auth: true
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ycensi'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run CI script
        run: yarn ci

      - name: Run unit tests
        run: yarn test

      - name: Build package
        run: yarn prepare

      - name: Publish package to GitHub
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          git config --global user.email "yurirobertcontato@gmail.com"
          git config --global user.name "ycensi"
          yarn release --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
